### ISSUE TITLE
[Bug] MN: Command "masternode start-alias" doesn't work on first time

### ISSUE THREAD

**Issue by AltcoinBaggins** [velesnetwork/veles-archive#21]
It has just been reported to Veles Code Discord server, that when the command `masternode start-alias` is run in the wallet for the first time, remote masternode stays in `PRE_ENABLED` state, but when run the second time it succeeds.

We've started an investigation onto this issue.

**Comment by AltcoinBaggins** [comment]
According to reports it most likely happens with versions v0.17.x - v0.17.0.22 included.

**Comment by xCryptoCash** [comment]
I'm using v0.17.0.21 win wallet,with Linux VPS MN, and for the 3 MNs I'm running I had to unlock collateral, and start alias at least twice for all 3 before the MN would go to enabled

**Comment by velescore** [comment]
I was also trying to setup MN atm. and it's really seem's that  you need to use "start-alias" two times before MN start to be enabled .

**Comment by mdfkbtc** [comment]
I was also trying to setup MN on version **"v0.17.0.22"** atm. and it's really seem's that  you need to use "start-alias" two times before MN start to be enabled..

**Comment by AltcoinBaggins** [comment]
We're attempting to repeatedly reproduce the bug and are in a process of investigation whether it's affecting only the GUI wallet (this led to discovery and fix of bug #22 in CLI wallet), fixes are scheduled to be released in upcoming v0.17.1.

**Comment by AltcoinBaggins** [comment]
The issue has been **solved**, patch added with merge #25, will be ported to official release v0.17.1 soon.

**Comment by mdfkbtc** [comment]
Good job Baggins ... nice work
