### ISSUE TITLE
v0.17.1-rc1

### ISSUE THREAD

**Issue by ghost** [velesnetwork/veles-archive#28]
I discovered an issue with the pre-release v0.17.1-rc1, happened twice now.

After this version was released i installed this ONLY as local wallet.

When MN changed status to NEW_START_REQUIRED in local wallet, i checked on MN and the status there was " MN successfully started"  
So when i started "alias MN" the status changed to PRE_ENABLED on local wallet, but this status stayed the same for hours. Meanwhile every now and then i checked on MN and the status there was still "MN successfully started".   I also did restart the "alias MN" again, but the status did not change for a long time again.  
Eventually the status did change to ENABLED but this took really long(i can't tell how long because i was not online when this happened).

After a few days the same incident happened again, and again i used the same procedure, only this time after about 3 hours i changed the local wallet back to the curent last stable version: v0.17.0.22 "Aged Amnesia"
So again before i restarted "alias MN" i checked on MN and the status was " MN successfully started" 
After i restarted "alias MN" in local wallet, the status from PRE_ENABLED to ENABLED took about 15 minutes.

**Comment by velesnetwork** [comment]
We're investigating the issue, it might be related to issues with current MN sync system, in a worst case scenario it will be solved when we port DIP3 - Deterministic Masternodes concept - from development branch of Dash, which will enable masternode list synced through blockchain and should prevent situations like the one above.

**Comment by velesnetwork** [comment]
DIP3 scheduled to be implemented in v18.1.

**Comment by velesnetwork** [comment]
Backported fix #34 to 17.1 wallet which should solve the issue.
