### ISSUE TITLE
Veles Core version v0.17.0.22

### ISSUE THREAD

**Issue by ghost** [velesnetwork/veles-archive#32]
There is an rpcworkqueue issue with this wallet, and perhaps with the new version as well..., which causes the masternode monitoring service at masternodecap.com to stop after some period of time.
There has been some communication between the team of VLS and masternodecap and a suggestion from the side of VLS team was that the number could be raised to solve this problem.  But after this it happened again. So it seems that raising the number will not solve the issue?

**Comment by velesnetwork** [comment]
Doesn't seem like a issue with the Veles Core daemon itself, the rpc work queue limit it's more a feature of new wallets than a bug, we'll be working on the article on how to correctly implement Veles daemon in high load environments.
