### ISSUE TITLE
v0.17.1-rc3 

### ISSUE THREAD

**Issue by ghost** [velesnetwork/veles-archive#33]
Long story short...this is basicly the same issue as i reported on v0.17.1-rc1.

MN status is "started"  but local wallet "alias mn" stays in pre_enabled state for a  long time. 

When switchted back to current stable version Veles Core version v0.17.0.22, "alias mn" went to enabled state in short time.

**Comment by velesnetwork** [comment]
This issue will be solved by porting Deterministic masternode concept DIP3, scheduled to be implemented in v18.1.

**Comment by velesnetwork** [comment]
Before the release v18.1 the masternode syncing problems should be improved by fix #34 to be back-ported to 17.1 wallet release which is to be released within a couple of days.
