### ISSUE TITLE
PR #25 for bug #20 is causing MN locked in PRE_ENABLED state

### ISSUE THREAD

**Issue by uhliksk** [velesnetwork/veles-archive#36]
Can't start new masternode in GUI wallet. All running masternodes dropped and locked in PRE_ENABLED state. It's new bug introduced in v0.17.1.

**Comment by velesnetwork** [comment]
The issue should be fixed in the v0.17.1.1 (current source of 0.17, binaries not released yet) where we've merged your fix #39 and deprecated MN activation helper task.
