### ISSUE TITLE
Invalid difficulty reported

### ISSUE THREAD

**Issue by atomminer** [velesnetwork/veles-archive#51]
velesd reports incorrect difficulty via getblockchaininfo call.

conf file:
server=1
listen=1
daemon=0
gen=0
rpcthreads=12
dbcache=5
maxconnections=10
deprecatedrpc=accounts
algo=sha256d

samples output of getblockchaininfo:
{"result":{"chain":"main","blocks":269390,"headers":269390,"bestblockhash":"6ceaa8d9e1000d6af7c1f697a62ff57dd5de1c80285281defd275a37e5f7caee","difficulty":3831.391509370843,"mediantime":1574118779,"verificationprogress":1.097842440893784e-05,"initialblockdownload":false,"chainwork":"00000000000000000000000000000000000000000000016d813667f86cc444f5","size_on_disk":224296637,"pruned":false,"softforks":[{"id":"bip34","version":2,"reject":{"status":true}},{"id":"bip66","version":3,"reject":{"status":true}},{"id":"bip65","version":4,"reject":{"status":true}}],"bip9_softforks":{"csv":{"status":"active","startTime":0,"timeout":9223372036854775807,"since":6048},"segwit":{"status":"active","startTime":0,"timeout":9223372036854775807,"since":6048}},"warnings":""},"error":null,"id":"1"}

decoding nBits from getblocktemplate provides accurate difficulty of 28118634.611017339 at the same time.

**Comment by AltcoinBaggins** [comment]
This is the expected behaviour, the `getblockchaininfo` command reports the difficuly of the algo that produced the last block found - for example, in the result above the bectblockhash is `6ceaa8d9e1000d6af7c1f697a62ff57dd5de1c80285281defd275a37e5f7caee` which is not sha256d hash, so the reported difficulty `3831.391509370843` was the difficulty of the algo that produced said block.

**Comment by atomminer** [comment]
what api call should be used to get the actual diff on the algo then?
should I keep decoding nBits from getblockstemplate to get actual diff every time I need it instead?

**Comment by mdfkbtc** [comment]
You can get actual diff with `getmininginfo` or with `getmultialgostatus`

**Comment by atomminer** [comment]
ok, a bit inconvenient, but I can work with that
